spring:
  application:
    name: health-checker
  datasource:
    url: jdbc:postgresql://${DB_SVC_NAME}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: ${SERVER_PORT}