spring:
  application:
    name: health-checker
  datasource:
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:5432/${DB_NAME:postgres}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8000