spring:
  application:
    name: health-checker
#  datasource:
#    url: jdbc:postgresql://${DB_SVC_NAME}/${DB_NAME}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update

server:
  port: ${SERVER_PORT:8000}

management:
  endpoints:
    web:
      exposure.include: "*"
      base-path: /monitoring
  endpoint:
    shutdown.enabled: true
    health: # общий статус приложения
      probes.enabled: true
      show-details: always
      show-components: always
  metrics:
    distribution:
      percentiles-histogram:
        all: true
        http.server.requests: true