apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: health-checker
spec:
  ingressClassName: nginx
  rules:
    - host: arch.homework
      http:
        paths:
          - backend:
              service:
                name: health-checker
                port:
                  number: 80
            path: /
            pathType: Prefix
