apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-cm
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
data:
  DB_NAME: "{{- .Values.postgresql.postgresDBName }}"
  DB_SVC_NAME: {{ .Release.Name }}-postgresql
  DB_USERNAME: "{{- .Values.postgresql.postgresUser }}"
  DB_PASSWORD: "{{- .Values.postgresql.postgresPassword }}"

