apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-cm
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
data:
  DB_NAME: "{{- .Values.application.environments.DB_NAME }}"
  DB_SVC_NAME: "{{ .Values.application.environments.DB_SVC_NAME }}"
  DB_USERNAME: "{{- .Values.application.environments.DB_USERNAME }}"
  SERVER_PORT: "8000"

