apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-cm
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
data:
  DB_NAME: "{{- .Values.postgresql.auth.database }}"
  DB_SVC_NAME: {{ .Release.Name }}-postgresql
  DB_USERNAME: "{{- .Values.postgresql.auth.username }}"
  SERVER_PORT: "8000"

