{{- $variables := .Values.env -}}
{{- if .Values.cronJobs -}}
  {{- range .Values.cronJobs }}
    {{- if .name }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .name }}
  labels:
  {{ include ".helm.labels" . | indent 4 }}
spec:
  schedule: "{{ .schedule }}"
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: cron-job-container
              image: "{{ .image }}"
              imagePullPolicy: IfNotPresent
              env:
            {{- range $name, $value := $variables }}
            {{- if not (empty $value) }}
                - name: {{ $name | quote }}
                  value: {{ $value | quote }}
            {{- end }}
            {{- end }}
              command:
{{ toYaml .command | indent 14 -}}

    {{- end }}
  {{- end }}
{{- end }}
