apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include ".helm.fullname" . }}
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.application.replicaCount }}
  strategy:
    type: {{ .Values.strategy.type }}
    {{- if eq "RollingUpdate" .Values.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge | default "1" }}
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable | default "0" }}
      {{- end}}
  selector:
    matchLabels:
      {{- include ".helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.application.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include ".helm.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.application.image.repository }}:{{ .Values.application.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: {{ .Values.application.targetPort | default "8000" }}
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: {{ .Values.application.targetPort | default "8000" }}
          resources:
            {{- toYaml .Values.application.resources | nindent 12 }}
          env:
            - name: DB_SVC_NAME
              value: {{ .Release.Name }}-postgresql
          {{- range $name, $value := $.Values.application.environments }}
          {{- if not (empty $value) }}
            - name: {{ $name | quote }}
              value: {{ $value | quote }}
          {{- end}}
          {{- end}}
          {{- if not (empty $.Values.application.secretEnv) }}
            {{- toYaml $.Values.application.secretEnv | nindent 12 }}
          {{- end}}
