# Default values for .helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

application:
  targetPort: 8000
  replicaCount: 2
  podAnnotations: {}
  image:
    repository: jakotoychubaev/young-rgb
    tag: v11
  resources:
    limits:
      cpu: "0.1"
      memory: "400Mi"
    requests:
      cpu: "0.1"
      memory: "200Mi"
  environments:
    DB_NAME: "health_checker"
    SERVER_PORT: 8000
    DB_USERNAME: "health_checker"
  secretEnv:
    - name: password
      valueFrom:
        secretKeyRef:
          name: db-config-secret
          key: password

nameOverride: ""
service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: arch.homework
      paths:
        - path: /
          pathType: Prefix

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: "1"
    maxUnavailable: "0"

postgresql:
  builtin: true
  auth:
    username: health_checker
    database: health_checker
    password: password
  shmVolume:
    sizeLimit: "1Gi"
  primary:
    resources:
      limits:
        memory: "1Gi"
        cpu: "1000m"
      requests:
        memory: "1Gi"
        cpu: "1000m"
      persistence:
        enabled: true
        storageClass: "standard"
        size: "1Gi"
  readReplicas:
    persistence:
      enabled: true
      storageClass: "standard"
      size: "1Gi"

jobInitDb:
  image: postgres
  tag: 12.17-alpine3.19
  imgPullPolicy: IfNotPresent