# Default values for .helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

application:
  targetPort: 8000
  replicaCount: 2
  podAnnotations: {}
  image:
    repository: jakotoychubaev/young-rgb
    tag: v13
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "0.1"
      memory: "200Mi"
  environments:
    DB_SVC_NAME: health-checker-app-postgresql
    DB_NAME: "postgres"
    SERVER_PORT: 8000
    DB_USERNAME: "postgres"
  secretEnv:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: health-checker-app-postgresql
          key: postgres-password

nameOverride: ""
service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: arch.homework
      paths:
        - path: /
          pathType: Prefix

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: "1"
    maxUnavailable: "0"

postgresql:
  builtin: true
  auth:
    username: postgres
    database: postgres
    password: password
  shmVolume:
    sizeLimit: "1Gi"
  primary:
    resources:
      limits:
        memory: "1Gi"
        cpu: "1000m"
      requests:
        memory: "1Gi"
        cpu: "1000m"
      persistence:
        enabled: true
        storageClass: "standard"
        size: "1Gi"
  readReplicas:
    persistence:
      enabled: true
      storageClass: "standard"
      size: "1Gi"

jobInitDb:
  image: postgres
  tag: 12.17-alpine3.19
  imgPullPolicy: IfNotPresent